version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/generators/11ty-app/template"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/generators/basic-app/template"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/generators/snowpack-app/template"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/generators/vite-app/template"
    schedule:
      interval: "weekly"
